Repository qiboteam/qibo, pull requests merged in 2022-12, with the labels that each got.

#725 Depolarizing channel: backend agnostic
  src/qibo/gates/channels.py
Labels: enhancement

#702 Error mitigation
  doc/source/api-reference/qibo.rst
  doc/source/code-examples/advancedexamples.rst
  src/qibo/models/__init__.py
  src/qibo/models/error_mitigation.py
  src/qibo/tests/test_models_error_mitigation.py
Labels: enhancement

#714 example quantum anomaly detection
  doc/source/code-examples/applications.rst
  doc/source/code-examples/tutorials/anomaly_detection/README.md
  doc/source/code-examples/tutorials/anomaly_detection/images
  examples/README.md
  examples/anomaly_detection/README.md
  examples/anomaly_detection/data/anomalous_data.npy
  examples/anomaly_detection/data/standard_data.npy
  examples/anomaly_detection/images/Fig1.png
  examples/anomaly_detection/images/Fig2.png
  examples/anomaly_detection/images/Fig3.png
  examples/anomaly_detection/images/Fig4.png
  examples/anomaly_detection/images/Fig5.png
  examples/anomaly_detection/images/Fig6.png
  examples/anomaly_detection/parameters/trained_params.npy
  examples/anomaly_detection/test.py
  examples/anomaly_detection/train.py
  examples/test_examples.py
Labels: enhancement

#724 Created Custom, Unitary and Kraus errors for NoiseModel
  doc/source/api-reference/qibo.rst
  src/qibo/noise.py
  src/qibo/tests/test_noise.py
  src/qibo/tests/test_states.py
Labels: enhancement

#734 Update vqregressor link in README.md
  examples/vqregressor/README.md
Labels: bug

#667 First implementation of the parameter shift rule
  src/qibo/derivative.py
  src/qibo/gates/abstract.py
  src/qibo/gates/gates.py
  src/qibo/models/circuit.py
  src/qibo/tests/test_derivative.py
  src/qibo/tests/test_gates_abstract.py
Labels: enhancement

#721 Liouville representation of quantum channels
  doc/source/api-reference/qibo.rst
  src/qibo/backends/numpy.py
  src/qibo/gates/channels.py
  src/qibo/quantum_info/__init__.py
  src/qibo/quantum_info/basis.py
  src/qibo/quantum_info/metrics.py
  src/qibo/tests/test_gates_channels.py
  src/qibo/tests/test_quantum_info_basis.py
Labels: enhancement

#739 Update `gate.init_kwargs` when setting new parameters
  src/qibo/gates/abstract.py
  src/qibo/gates/gates.py
  src/qibo/tests/test_gates_abstract.py
Labels: bug

#740 Add IONQ gates to Qibo
  doc/source/api-reference/qibo.rst
  src/qibo/backends/npmatrices.py
  src/qibo/gates/gates.py
  src/qibo/tests/test_gates_gates.py
Labels: enhancement

#735 Rescaled parameter shift rule
  src/qibo/derivative.py
  src/qibo/tests/test_derivative.py
Labels: enhancement

#741 Add derivative to qibo docs
  doc/source/api-reference/qibo.rst
  src/qibo/derivative.py
  src/qibo/tests/test_derivative.py
Labels: documentation

#746 Ubuntu font in the documentation
  doc/source/conf.py
Labels: documentation

#745 Moved "qibo release" to the doc's side-bar
  doc/source/conf.py
  doc/source/index.rst
Labels: documentation

#742 Publishing workflow
  .github/workflows/publish.yml
Labels: documentation

#750 Thermal relaxation channel
  src/qibo/gates/channels.py
  src/qibo/tests/test_gates_channels.py
Labels: bug

#751 rm Ubuntu font from furo configuration
  doc/source/conf.py
Labels: documentation

#749 including more documentation of the loss functions for QAOA.
  src/qibo/models/variational.py
Labels: documentation
