Repository qiboteam/qibo, pull requests merged in 2022-11, with the labels that each got.

#660 Metrics
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/__init__.py
  src/qibo/quantum_info/metrics.py
  src/qibo/quantum_info/utils.py
  src/qibo/tests/test_quantum_info.py
Labels: enhancement

#636 Customize qaoa loss
  src/qibo/models/utils.py
  src/qibo/models/variational.py
  src/qibo/tests/test_models_variational.py
Labels: enhancement

#700 Added furo as extras_require in setup.py
  setup.py
Labels: documentation

#690 From Standard to Furo doc's theme
  doc/source/conf.py
  setup.py
Labels: documentation

#706 Fix documentation
  doc/source/api-reference/qibo.rst
  src/qibo/gates/gates.py
Labels: documentation

#708 Draw FusedGate
  src/qibo/gates/gates.py
  src/qibo/gates/special.py
  src/qibo/models/circuit.py
  src/qibo/tests/test_models_circuit_fuse.py
Labels: enhancement

#707 add iswap gate
  doc/source/api-reference/qibo.rst
  src/qibo/backends/npmatrices.py
  src/qibo/gates/gates.py
  src/qibo/models/circuit.py
  src/qibo/tests/test_gates_gates.py
Labels: enhancement

#716 fixing typo in docs appendix
  doc/source/appendix/citing-qibo.rst
Labels: bug, documentation

#699 Add FusedGate to circuit
  src/qibo/gates/gates.py
  src/qibo/gates/special.py
  src/qibo/models/circuit.py
  src/qibo/tests/test_models_circuit_fuse.py
Labels: enhancement
