Repository qiboteam/qibo, pull requests merged in 2023-11, with the labels that each got.

#1052 Calculation of `quantum_info.haar_integral` exactly
  src/qibo/models/error_mitigation.py
  src/qibo/quantum_info/metrics.py
  src/qibo/quantum_info/utils.py
  tests/test_quantum_info_utils.py
Labels: documentation, enhancement

#1059 Creation of `qibo.models.encodings` and implementation of `unary_encoder`
  doc/source/api-reference/qibo.rst
  src/qibo/models/__init__.py
  src/qibo/models/encodings.py
  tests/test_models_encodings.py
Labels: documentation, enhancement

#1074 Fix `matrix()` method for `gates.GeneralizedfSim`
  src/qibo/backends/npmatrices.py
Labels: bug

#1057 Implementation of function that samples `U3` phases from Haar distribution
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/random_ensembles.py
  tests/test_quantum_info_random.py
Labels: documentation, enhancement

#1055 Move transpiler from `Qibolab` to `Qibo`
  doc/source/code-examples/advancedexamples.rst
  poetry.lock
  src/qibo/transpiler/__init__.py
  src/qibo/transpiler/abstract.py
  src/qibo/transpiler/blocks.py
  src/qibo/transpiler/exceptions.py
  src/qibo/transpiler/optimizer.py
  src/qibo/transpiler/pipeline.py
  src/qibo/transpiler/placer.py
  src/qibo/transpiler/router.py
  src/qibo/transpiler/star_connectivity.py
  src/qibo/transpiler/unitary_decompositions.py
  src/qibo/transpiler/unroller.py
  tests/test_transpiler_abstract.py
  tests/test_transpiler_blocks.py
  tests/test_transpiler_optimizer.py
  tests/test_transpiler_pipeline.py
  tests/test_transpiler_placer.py
  tests/test_transpiler_router.py
  tests/test_transpiler_star_connectivity.py
  tests/test_transpiler_unitary_decompositions.py
  tests/test_transpiler_unroller.py
Labels: transpiler

#1071 Unary encoder for random Gaussian states
  doc/source/api-reference/qibo.rst
  src/qibo/models/encodings.py
  tests/test_models_encodings.py
Labels: documentation, enhancement

#1090 Fix ``Clifford`` label on controlled gates
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: bug

#1092 Inclusion of all cached gate matrices into ``QiboMatrices``
  src/qibo/backends/__init__.py
Labels: enhancement

#1093 Add decomposition for ``gates.FSWAP``
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: enhancement

#1084 Sabre with measurements
  src/qibo/gates/measurements.py
  src/qibo/transpiler/blocks.py
  src/qibo/transpiler/router.py
  tests/test_transpiler_router.py
Labels: transpiler

#1095 Add user choice between `U3` or `GPI2` as single-qubit native gate
  doc/source/code-examples/advancedexamples.rst
  src/qibo/transpiler/abstract.py
  src/qibo/transpiler/decompositions.py
  src/qibo/transpiler/pipeline.py
  src/qibo/transpiler/placer.py
  src/qibo/transpiler/router.py
  src/qibo/transpiler/unroller.py
  tests/test_transpiler_abstract.py
  tests/test_transpiler_blocks.py
  tests/test_transpiler_decompositions.py
  tests/test_transpiler_pipeline.py
  tests/test_transpiler_router.py
  tests/test_transpiler_unroller.py
Labels: transpiler

#1047 Double bracket iterations
  doc/source/api-reference/qibo.rst
  doc/source/code-examples/applications-by-algorithm.rst
  doc/source/code-examples/applications-by-topic.rst
  doc/source/code-examples/applications.rst
  doc/source/code-examples/tutorials/dbi/dbi.ipynb
  examples/dbi/dbi.ipynb
  poetry.lock
  pyproject.toml
  src/qibo/models/dbi/double_bracket.py
  tests/test_models_dbi.py
Labels: enhancement
