Repository qiboteam/qibo, pull requests merged in 2023-03, with the labels that each got.

#807 multi-qubit Pauli noise channel
  doc/source/api-reference/qibo.rst
  src/qibo/gates/channels.py
  src/qibo/quantum_info/metrics.py
  tests/test_gates_channels.py
Labels: enhancement

#789 Noise conditions
  doc/source/code-examples/advancedexamples.rst
  src/qibo/noise.py
  tests/test_noise.py
Labels: enhancement

#805 Fix circuit copy modifying the original queue
  src/qibo/models/circuit.py
  tests/test_models_circuit.py
Labels: bug

#819 Depolarizing channel
  src/qibo/backends/abstract.py
  src/qibo/backends/numpy.py
  src/qibo/gates/channels.py
  tests/test_gates_channels.py
Labels: bug

#821 Removed nlop and added direct method from scipy.
  poetry.lock
  pyproject.toml
  src/qibo/noise_model.py
Labels: bug

#799 Measurement in Pauli basis
  src/qibo/backends/numpy.py
  src/qibo/gates/abstract.py
  src/qibo/gates/gates.py
  src/qibo/gates/measurements.py
  src/qibo/models/circuit.py
  tests/test_gates_gates.py
  tests/test_measurements.py
  tests/test_models_circuit_execution.py
Labels: enhancement

#823 Depolarizing Channel
  src/qibo/backends/abstract.py
  src/qibo/backends/numpy.py
  src/qibo/gates/channels.py
  tests/test_gates_channels.py
Labels: bug

#810 `ReadoutErrorChannel` class + move `KrausChannel` methods to `Channel`
  doc/source/api-reference/qibo.rst
  pyproject.toml
  src/qibo/gates/channels.py
  src/qibo/gates/gates.py
  src/qibo/noise.py
  tests/test_gates_channels.py
  tests/test_models_circuit.py
  tests/test_noise.py
Labels: bug, documentation, enhancement

#827 function that approximates Kraus operators as probabilistic sum of unitaries
  doc/source/api-reference/qibo.rst
  src/qibo/gates/channels.py
  src/qibo/quantum_info/metrics.py
  src/qibo/quantum_info/random_ensembles.py
  src/qibo/quantum_info/superoperator_transformations.py
  src/qibo/quantum_info/utils.py
  tests/test_quantum_info_random.py
  tests/test_quantum_info_superoperator_transformations.py
Labels: documentation, enhancement

#833 Pauli-Liouville transformations
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/metrics.py
  src/qibo/quantum_info/superoperator_transformations.py
  tests/test_gates_channels.py
  tests/test_quantum_info_superoperator_transformations.py
Labels: documentation, enhancement

#832 `to_choi` for Reset and ThermalRelaxation
  src/qibo/backends/numpy.py
  src/qibo/gates/channels.py
  tests/test_gates_channels.py
Labels: documentation, enhancement

#838 Add sparse representation to `quantum_info.basis`
  src/qibo/quantum_info/basis.py
  src/qibo/quantum_info/superoperator_transformations.py
  tests/test_quantum_info_basis.py
  tests/test_quantum_info_superoperator_transformations.py
Labels: enhancement

#840 Based on qibo section in docs appendix
  doc/source/appendix/citing-qibo.rst
Labels: documentation

#842 Chi-matrix representation
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/superoperator_transformations.py
  tests/test_quantum_info_superoperator_transformations.py
Labels: documentation, enhancement
