Repository qiboteam/qibo, pull requests merged in 2023-06, with the labels that each got.

#915 Add `concurrence` and `entanglement_of_formation` to `quantum_info.metrics`
  doc/source/api-reference/qibo.rst
  src/qibo/models/error_mitigation.py
  src/qibo/quantum_info/metrics.py
  src/qibo/quantum_info/utils.py
  tests/test_quantum_info_metrics.py
Labels: documentation, enhancement

#921 Add `impurity`, `infidelity`, and `process_infidelity` to `quantum_info.metrics`
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/metrics.py
  tests/test_quantum_info_metrics.py
Labels: documentation, enhancement

#924 `quantum_info.metrics.fidelity` generalized for mixed states
  src/qibo/backends/numpy.py
  src/qibo/quantum_info/metrics.py
  tests/test_quantum_info_metrics.py
  tests/test_quantum_info_utils.py
Labels: documentation, enhancement

#931 Fix test in `master` branch
  tests/test_quantum_info_metrics.py
Labels: bug

#936 Rename `Circuit.with_noise` method as `Circuit.with_pauli_noise`
  doc/source/code-examples/advancedexamples.rst
  src/qibo/models/circuit.py
  tests/test_models_circuit.py
  tests/test_models_circuit_features.py
  tests/test_models_circuit_noise.py
  tests/test_models_distcircuit.py
Labels: documentation, enhancement

#943 Remove old channel initialisations and warnings
  src/qibo/gates/channels.py
  tests/test_gates_channels.py
Labels: documentation, enhancement

#950 Fixing bug in `asmatrix_fused` with `CupyBackend`
  src/qibo/backends/numpy.py
  tests/test_models_variational.py
  tests/test_quantum_info_superoperator_transformations.py
Labels: bug

#872 `Stinespring` superoperator representation
  doc/source/api-reference/qibo.rst
  src/qibo/gates/channels.py
  src/qibo/quantum_info/superoperator_transformations.py
  tests/test_gates_abstract.py
  tests/test_quantum_info_random.py
  tests/test_quantum_info_superoperator_transformations.py
Labels: documentation, enhancement

#944 Add (fast) Hadamard Transform to `quantum_info.utils`
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/utils.py
  tests/test_quantum_info_utils.py
Labels: documentation, enhancement

#953 Generalizaton of the `MS` gate
  src/qibo/backends/npmatrices.py
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: documentation, enhancement

#949 Add Diamond norm to `quantum_info.metrics`
  doc/source/api-reference/qibo.rst
  poetry.lock
  pyproject.toml
  src/qibo/quantum_info/metrics.py
  tests/test_quantum_info_metrics.py
Labels: documentation, enhancement, dependencies

#954 Add `Givens` gate
  doc/source/api-reference/qibo.rst
  src/qibo/backends/npmatrices.py
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: documentation, enhancement
