Repository qiboteam/qibo, pull requests merged in 2023-10, with the labels that each got.

#1022 Fix `apply_channel()` for statevector simulation
  src/qibo/backends/numpy.py
  tests/test_measurements_probabilistic.py
  tests/test_models_circuit_features.py
  tests/test_models_circuit_noise.py
Labels: bug

#1035 Add custom `decompose` method to `gates.U3` and `gates.CZ`
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: documentation, enhancement

#1042 Rename `gates.RXY` as `gates.RXXYY` and fix `gates.SYC` docstring
  doc/source/api-reference/qibo.rst
  src/qibo/backends/npmatrices.py
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: documentation

#1043 Add `order` parameter to `backend.calculate_norm`
  doc/source/api-reference/qibo.rst
  src/qibo/backends/abstract.py
  src/qibo/backends/numpy.py
  src/qibo/backends/tensorflow.py
  src/qibo/quantum_info/metrics.py
  src/qibo/quantum_info/superoperator_transformations.py
  src/qibo/quantum_info/utils.py
  tests/test_callbacks.py
  tests/test_gates_channels.py
  tests/test_models_circuit_features.py
  tests/test_quantum_info_metrics.py
  tests/test_quantum_info_random.py
Labels: documentation, enhancement

#1041 Native gate for Quantinuum platform
  doc/source/api-reference/qibo.rst
  src/qibo/backends/npmatrices.py
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: documentation, enhancement

#1044 Implementation of `backend.calculate_overlap_density_matrix` in `numpy` backend
  src/qibo/backends/abstract.py
  src/qibo/backends/numpy.py
  src/qibo/callbacks.py
  tests/test_callbacks.py
Labels: documentation, enhancement

#1062 Fix sphinx compilation warnings/errors
  doc/source/api-reference/qibo.rst
  examples/mvc/README.md
  src/qibo/gates/special.py
Labels: documentation

#1061 Avoid tutorials repetition
  doc/source/code-examples/applications-by-algorithm.rst
  doc/source/code-examples/applications-by-topic.rst
  doc/source/code-examples/applications.rst
Labels: documentation

#1045 New implementation of `EntanglementEntropy` callback
  src/qibo/backends/abstract.py
  src/qibo/backends/numpy.py
  src/qibo/backends/tensorflow.py
  src/qibo/callbacks.py
  src/qibo/quantum_info/metrics.py
  tests/test_callbacks.py
Labels: documentation, enhancement
