Repository qiboteam/qibo, pull requests merged in 2023-07, with the labels that each got.

#952 Add `clifford` label to gates
  src/qibo/gates/abstract.py
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: documentation, enhancement

#959 Add `SX`, `RBS`, `RZX`, `ECR`, and `SYC` gates
  doc/source/api-reference/qibo.rst
  src/qibo/backends/__init__.py
  src/qibo/backends/npmatrices.py
  src/qibo/gates/gates.py
  src/qibo/quantum_info/metrics.py
  tests/test_gates_gates.py
Labels: documentation, enhancement

#968 New `unitary` attribute to gates and `KrausChannel` checks if all operators are unitaries
  src/qibo/gates/abstract.py
  src/qibo/gates/channels.py
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: bug, documentation, enhancement

#969 Implementation of `AmplitudeDampingChannel`
  doc/source/api-reference/qibo.rst
  src/qibo/backends/numpy.py
  src/qibo/gates/channels.py
  src/qibo/noise.py
  tests/test_gates_channels.py
  tests/test_noise.py
Labels: documentation, enhancement

#972 Update docs for dagger
  src/qibo/gates/abstract.py
  src/qibo/models/circuit.py
Labels: documentation

#971 Import `Circuit` directly from `qibo`
  README.md
  doc/source/code-examples/advancedexamples.rst
  doc/source/code-examples/examples.rst
  doc/source/code-examples/tutorials/qfiae/qfiae_demo.ipynb
  doc/source/getting-started/quickstart.rst
  examples/3_tangle/canonizator.py
  examples/anomaly_detection/test.py
  examples/anomaly_detection/train.py
  examples/bell-variational/functions.py
  examples/grover/example1.py
  examples/grover/example2.py
  examples/grover/example3.py
  examples/grover3sat/functions.py
  examples/hash-grover/functions.py
  examples/qfiae/qfiae_demo.ipynb
  examples/qfiae/utils_qfiae.py
  examples/qfiae/vqregressor_linear_ansatz.py
  examples/qsvd/qsvd.py
  examples/reuploading_classifier/qlassifier.py
  examples/shor/functions.py
  examples/unary/functions.py
  examples/variational_classifier/qclassifier.py
  examples/vqregressor/vqregressor.py
  src/qibo/__init__.py
  src/qibo/derivative.py
  src/qibo/gates/channels.py
  src/qibo/hamiltonians/hamiltonians.py
  src/qibo/models/circuit.py
  src/qibo/models/error_mitigation.py
  src/qibo/models/grover.py
  src/qibo/models/iqae.py
  src/qibo/models/qcnn.py
  src/qibo/noise.py
  src/qibo/quantum_info/random_ensembles.py
  tests/test_derivative.py
  tests/test_dill.py
  tests/test_gates_density_matrix.py
  tests/test_hamiltonians.py
  tests/test_hamiltonians_symbolic.py
  tests/test_models_circuit.py
  tests/test_models_circuit_backpropagation.py
  tests/test_models_circuit_execution.py
  tests/test_models_circuit_features.py
  tests/test_models_circuit_fuse.py
  tests/test_models_circuit_noise.py
  tests/test_models_circuit_parametrized.py
  tests/test_models_circuit_qasm.py
  tests/test_models_circuit_qasm_cirq.py
  tests/test_models_distcircuit.py
  tests/test_models_distcircuit_execution.py
  tests/test_models_error_mitigation.py
  tests/test_models_grover.py
  tests/test_models_iqae.py
  tests/test_models_qcnn.py
  tests/test_noise.py
  tests/test_quantum_info_metrics.py
  tests/test_quantum_info_utils.py
  tests/test_states.py
Labels: documentation, enhancement

#975 Add delay pulse option to `Align` gate
  doc/source/api-reference/qibo.rst
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: documentation, enhancement

#976 Add `PhaseDampingChannel`
  doc/source/api-reference/qibo.rst
  src/qibo/gates/channels.py
  src/qibo/noise.py
  tests/test_gates_channels.py
  tests/test_noise.py
Labels: documentation, enhancement
