Repository qiboteam/qibo, pull requests merged in 2023-05, with the labels that each got.

#871 `basis` flag in `random_density_matrix`
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/random_ensembles.py
  tests/test_quantum_info_random.py
Labels: documentation, enhancement

#875 Modify quantum_info tests
  src/qibo/quantum_info/random_ensembles.py
  tests/test_gates_special.py
  tests/test_hamiltonians_terms.py
  tests/test_hamiltonians_trotter.py
  tests/test_measurements_collapse.py
  tests/test_models_distcircuit_execution.py
  tests/test_models_qft.py
  tests/test_models_variational.py
  tests/test_quantum_info_metrics.py
  tests/test_quantum_info_random.py
  tests/test_states.py
Labels: enhancement

#882 Fix `test_derivative.py` for `cupy` backend
  src/qibo/derivative.py
  tests/test_derivative.py
Labels: bug, documentation

#876 Generalize channels
  src/qibo/gates/channels.py
  src/qibo/noise.py
  src/qibo/noise_model.py
  tests/test_gates_abstract.py
  tests/test_gates_channels.py
  tests/test_noise.py
  tests/test_quantum_info_basis.py
Labels: documentation, enhancement

#888 Add `H`, `S`, `SDG`, and `CNOT` to `QiboMatrices`
  src/qibo/backends/__init__.py
Labels: enhancement

#889 `DepolarizingChannel` inherits `PauliNoiseChannel`
  src/qibo/gates/channels.py
Labels: enhancement

#890 `ThermalRelaxationChannel` fix for `cupy` backend
  src/qibo/gates/channels.py
  tests/test_gates_channels.py
Labels: bug

#868 Calibration matrix for readout mitigation
  doc/source/api-reference/qibo.rst
  doc/source/code-examples/advancedexamples.rst
  src/qibo/models/error_mitigation.py
  tests/test_models_error_mitigation.py
Labels: documentation, enhancement

#896 Fix `sphinx` errors and warnings
  src/qibo/backends/abstract.py
  src/qibo/derivative.py
  src/qibo/noise.py
  src/qibo/quantum_info/superoperator_transformations.py
Labels: documentation

#883 Expressibility of parameterized quantum circuits
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/metrics.py
  src/qibo/quantum_info/utils.py
  tests/test_quantum_info_metrics.py
  tests/test_quantum_info_utils.py
Labels: documentation, enhancement

#906 Minor improvements to `quantum_info` documentation
  doc/source/api-reference/qibo.rst
  src/qibo/models/circuit.py
  src/qibo/quantum_info/basis.py
  src/qibo/quantum_info/metrics.py
  src/qibo/quantum_info/random_ensembles.py
  src/qibo/quantum_info/superoperator_transformations.py
  src/qibo/quantum_info/utils.py
Labels: documentation

#904 Add elements order to `pauli_basis`
  src/qibo/gates/channels.py
  src/qibo/quantum_info/basis.py
  src/qibo/quantum_info/random_ensembles.py
  src/qibo/quantum_info/superoperator_transformations.py
  tests/test_gates_channels.py
  tests/test_quantum_info_basis.py
  tests/test_quantum_info_random.py
  tests/test_quantum_info_superoperator_transformations.py
Labels: enhancement

#912 Fix `test_entropy` for `cupy` backend
  src/qibo/quantum_info/metrics.py
  tests/test_quantum_info_metrics.py
Labels: bug

#894 Workflow for selfhosted GPU (testing)
  .github/workflows/selfhosted.yml
  poetry.lock
  pyproject.toml
  selfhosted
Labels: do not merge, run-on-sim

#911 Add `bures_angle` and `bures_distance` to `quantum_info.metrics`
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/metrics.py
  tests/test_quantum_info_basis.py
  tests/test_quantum_info_metrics.py
Labels: documentation, enhancement

#919 Add `entanglement_entropy` to `quantum_info.metrics`
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/metrics.py
  tests/test_quantum_info_metrics.py
Labels: documentation, enhancement

#918 Fix repeated execution
  src/qibo/backends/numpy.py
Labels: bug

#905 Fix `tensorflow` warnings in documentation examples
  doc/source/code-examples/advancedexamples.rst
  src/qibo/models/qgan.py
  tests/test_models_circuit_backpropagation.py
  tests/test_models_circuit_parametrized.py
Labels: bug, documentation
