Repository qiboteam/qibo, pull requests merged in 2024-08, with the labels that each got.

#1407 Fix seed of two tests in `quantum_info`
  tests/test_backends_clifford.py
  tests/test_quantum_info_metrics.py
Labels: bug, quantum_info module

#1417 Fix root cause of bug reported in PR #1412
  src/qibo/backends/numpy.py
  src/qibo/measurements.py
  src/qibo/result.py
Labels: bug

#1373 Add `gates.GeneralizedRBS` gate
  doc/source/api-reference/qibo.rst
  poetry.lock
  src/qibo/backends/npmatrices.py
  src/qibo/backends/numpy.py
  src/qibo/gates/gates.py
  src/qibo/transpiler/decompositions.py
  tests/test_gates_gates.py
Labels: documentation, enhancement

#1422 Add `gates.CNOT` as a native gate in gate decomposition
  src/qibo/transpiler/decompositions.py
  src/qibo/transpiler/unroller.py
  tests/test_transpiler_unroller.py
Labels: enhancement, transpiler

#1430 Fix default backend loading
  src/qibo/backends/__init__.py
  tests/conftest.py
Labels: bug

#1428 Improved docs of `Hamiltonian` and `Gradients` modules
  doc/source/api-reference/qibo.rst
  src/qibo/derivative.py
  src/qibo/hamiltonians/abstract.py
  src/qibo/hamiltonians/hamiltonians.py
  src/qibo/hamiltonians/models.py
  src/qibo/symbols.py
Labels: documentation
