Repository qiboteam/qibo, pull requests merged in 2024-07, with the labels that each got.

#1379 Allow `Circuit` `kwargs` in `models.encodings`
  src/qibo/models/encodings.py
  tests/test_models_encodings.py
Labels: enhancement

#1276 Autodifferentiation support for `PytorchBackend`
  src/qibo/backends/npmatrices.py
  src/qibo/backends/numpy.py
  src/qibo/backends/pytorch.py
  src/qibo/backends/tensorflow.py
  src/qibo/derivative.py
  src/qibo/gates/channels.py
  src/qibo/gates/gates.py
  src/qibo/hamiltonians/hamiltonians.py
  src/qibo/measurements.py
  src/qibo/models/dbi/double_bracket.py
  src/qibo/models/dbi/utils.py
  src/qibo/models/dbi/utils_dbr_strategies.py
  src/qibo/models/encodings.py
  src/qibo/models/error_mitigation.py
  src/qibo/models/variational.py
  src/qibo/optimizers.py
  src/qibo/quantum_info/basis.py
  src/qibo/quantum_info/entanglement.py
  src/qibo/quantum_info/entropies.py
  src/qibo/quantum_info/metrics.py
  src/qibo/quantum_info/quantum_networks.py
  src/qibo/quantum_info/random_ensembles.py
  src/qibo/quantum_info/superoperator_transformations.py
  src/qibo/quantum_info/utils.py
  src/qibo/result.py
  src/qibo/transpiler/unitary_decompositions.py
  tests/test_backends.py
  tests/test_callbacks.py
  tests/test_derivative.py
  tests/test_gates_channels.py
  tests/test_gates_density_matrix.py
  tests/test_gates_gates.py
  tests/test_hamiltonians.py
  tests/test_hamiltonians_terms.py
  tests/test_hamiltonians_trotter.py
  tests/test_measurements_collapse.py
  tests/test_models_circuit_execution.py
  tests/test_models_circuit_features.py
  tests/test_models_circuit_parametrized.py
  tests/test_models_dbi.py
  tests/test_models_dbi_utils.py
  tests/test_models_encodings.py
  tests/test_models_error_mitigation.py
  tests/test_models_qft.py
  tests/test_models_variational.py
  tests/test_noise.py
  tests/test_quantum_info_basis.py
  tests/test_quantum_info_entanglement.py
  tests/test_quantum_info_entropies.py
  tests/test_quantum_info_metrics.py
  tests/test_quantum_info_quantum_networks.py
  tests/test_quantum_info_random.py
  tests/test_quantum_info_superoperator_transformations.py
  tests/test_quantum_info_utils.py
  tests/test_transpiler_decompositions.py
  tests/test_transpiler_unitary_decompositions.py
Labels: enhancement

#1390 Move `partial_trace` and `matrix_exponentiation` from `backend` methods to standalone functions in `quantum_info.linalg_operations`
  doc/source/api-reference/qibo.rst
  src/qibo/backends/abstract.py
  src/qibo/backends/numpy.py
  src/qibo/backends/pytorch.py
  src/qibo/backends/tensorflow.py
  src/qibo/hamiltonians/hamiltonians.py
  src/qibo/models/dbi/double_bracket.py
  src/qibo/quantum_info/__init__.py
  src/qibo/quantum_info/entanglement.py
  src/qibo/quantum_info/entropies.py
  src/qibo/quantum_info/linalg_operations.py
  src/qibo/quantum_info/operations.py
  tests/test_callbacks.py
  tests/test_gates_channels.py
  tests/test_measurements_probabilistic.py
  tests/test_quantum_info_operations.py
  tests/test_transpiler_unitary_decompositions.py
Labels: enhancement, quantum_info module

#1106 Gate set tomography
  doc/source/api-reference/qibo.rst
  doc/source/code-examples/advancedexamples.rst
  poetry.lock
  src/qibo/quantum_info/superoperator_transformations.py
  src/qibo/tomography/__init__.py
  src/qibo/tomography/gate_set_tomography.py
  tests/test_tomography_gate_set_tomography.py
Labels: documentation, enhancement

#1244 refactor `QuantumNetwork` to support general quantum networks
  doc/source/api-reference/qibo.rst
  doc/source/code-examples/tutorials/quantum_networks/README.md
  src/qibo/quantum_info/quantum_networks.py
  tests/test_quantum_info_quantum_networks.py
Labels: enhancement, quantum_info module

#1404 Apply channel for Clifford circuits with `cupy`
  src/qibo/backends/clifford.py
Labels: bug

#1399 Adjusting clifford condition in GPI2
  src/qibo/gates/gates.py
Labels: enhancement

#1394 Fix math erros in `models.dbi.double_bracket` docstrings
  src/qibo/models/dbi/double_bracket.py
Labels: bug, dependencies

#1393 Introduce circuit `kwargs` to `QFT` class
  src/qibo/models/qft.py
  tests/test_models_qft.py
Labels: enhancement

#1378 Fix backend usage in DBI intro notebook
  examples/dbi/dbi_tutorial_basic_intro.ipynb
Labels: bug

#1398 Fix Looping Behavior in Qibo SABRE
  src/qibo/transpiler/router.py
  tests/test_transpiler_router.py
Labels: bug, transpiler
