Repository qiboteam/qibo, pull requests merged in 2024-03, with the labels that each got.

#1157 Client backends for the remote execution of circuits
  doc/source/api-reference/qibo.rst
  poetry.lock
  pyproject.toml
  src/qibo/backends/__init__.py
  src/qibo/models/circuit.py
  tests/test_models_circuit_qasm.py
Labels: enhancement

#1207 QASM parser
  poetry.lock
  pyproject.toml
  src/qibo/config.py
  src/qibo/models/_openqasm.py
  src/qibo/models/circuit.py
  tests/test_measurements.py
  tests/test_models_circuit.py
  tests/test_models_circuit_qasm.py
Labels: enhancement

#1227 Creates `IBMQNoiseModel`
  doc/source/api-reference/qibo.rst
  doc/source/code-examples/advancedexamples.rst
  poetry.lock
  pyproject.toml
  src/qibo/gates/channels.py
  src/qibo/noise.py
  tests/test_backends_clifford.py
  tests/test_models_circuit_features.py
  tests/test_models_error_mitigation.py
  tests/test_noise.py
Labels: documentation, enhancement

#1248 Integrate `CliffordBackend` and `stim`
  doc/source/api-reference/qibo.rst
  poetry.lock
  pyproject.toml
  src/qibo/backends/clifford.py
  src/qibo/quantum_info/clifford.py
  tests/test_backends_clifford.py
Labels: documentation, dependencies, quantum_info module

#1245 Fix and speed-up DBI tests
  src/qibo/models/dbi/utils.py
  tests/test_models_dbi.py
  tests/test_models_dbi_utils.py
Labels: bug

#1255 Simplified `_Queue` append
  src/qibo/models/circuit.py
  tests/test_models_circuit.py
Labels: enhancement

#1262 Fix qibolab backend
  src/qibo/backends/__init__.py
Labels: bug

#1260 Add `entangling_layer` to `models.encodings`
  doc/source/api-reference/qibo.rst
  src/qibo/models/__init__.py
  src/qibo/models/encodings.py
  src/qibo/quantum_info/random_ensembles.py
  tests/test_models_encodings.py
Labels: enhancement

#1250 Fix deep copy of `gates.M` in `Circuit.copy()`
  src/qibo/models/circuit.py
  tests/test_transpiler_router.py
Labels: bug

#1270 Remove `dill` dependency
  poetry.lock
  pyproject.toml
  tests/test_dill.py
Labels: dependencies

#1278 Standardize images in encoding documentation
  doc/source/api-reference/qibo.rst
Labels: documentation

#1259 Minor improvement to `quantum_info.random_clifford`
  src/qibo/gates/abstract.py
  src/qibo/quantum_info/random_ensembles.py
Labels: enhancement, quantum_info module

#1257 Update `gate.clifford` value in rotations given a new angle
  src/qibo/gates/abstract.py
  src/qibo/gates/gates.py
  src/qibo/models/error_mitigation.py
  tests/test_gates_gates.py
  tests/test_models_error_mitigation.py
Labels: bug

#1273 Improving documentation of `models.encodings.entangling_layer`
  doc/source/_static/entangling_layer.png
  doc/source/api-reference/qibo.rst
Labels: documentation

#1281 Fix doc deployment by moving `torch` import
  src/qibo/backends/pytorch.py
Labels: bug
