Repository qiboteam/qibo, pull requests merged in 2024-06, with the labels that each got.

#1269 Dbi cost functions
  doc/source/code-examples/applications-by-algorithm.rst
  doc/source/code-examples/applications-by-topic.rst
  doc/source/code-examples/applications.rst
  doc/source/code-examples/tutorials/dbi/README.md
  doc/source/code-examples/tutorials/dbi/dbi.ipynb
  doc/source/code-examples/tutorials/dbi/dbi_cost_functions.ipynb
  doc/source/code-examples/tutorials/dbi/dbi_gradient_descent_strategies.ipynb
  doc/source/code-examples/tutorials/dbi/dbi_group_commutator_tests.ipynb
  doc/source/code-examples/tutorials/dbi/dbi_scheduling.ipynb
  doc/source/code-examples/tutorials/dbi/dbi_strategies_compare.ipynb
  doc/source/code-examples/tutorials/dbi/dbi_strategy_Ising_model.ipynb
  doc/source/code-examples/tutorials/dbi/dbi_strategy_Pauli-Z.ipynb
  doc/source/code-examples/tutorials/dbi/dbi_tutorial_basic_intro.ipynb
  examples/dbi/README.md
  examples/dbi/dbi_cost_functions.ipynb
  examples/dbi/dbi_gradient_descent_strategies.ipynb
  examples/dbi/dbi_group_commutator_tests.ipynb
  examples/dbi/dbi_scheduling.ipynb
  examples/dbi/dbi_strategies_compare.ipynb
  examples/dbi/dbi_strategy_Ising_model.ipynb
  examples/dbi/dbi_strategy_Pauli-Z.ipynb
  examples/dbi/dbi_tutorial_basic_intro.ipynb
  poetry.lock
  pyproject.toml
  src/qibo/models/dbi/double_bracket.py
  src/qibo/models/dbi/utils.py
  src/qibo/models/dbi/utils_dbr_strategies.py
  src/qibo/models/dbi/utils_scheduling.py
  tests/test_models_dbi.py
  tests/test_models_dbi_utils.py
Labels: documentation, enhancement

#1280 Add `gates.gate.CCZ`
  doc/source/api-reference/qibo.rst
  src/qibo/backends/__init__.py
  src/qibo/backends/npmatrices.py
  src/qibo/gates/gates.py
  src/qibo/transpiler/decompositions.py
  tests/test_gates_gates.py
Labels: documentation, enhancement

#1346 Fix CMA callback
  src/qibo/optimizers.py
  tests/test_models_variational.py
Labels: bug

#1355 Decomposition of `TOFFOLI` into `CNOT`, `T`, `TDG`, and `H`
  src/qibo/transpiler/decompositions.py
  tests/test_cirq.py
  tests/test_gates_gates.py
Labels: enhancement

#1360 Fix value of the spectrum returned in the `quantum_info.entropies.von_neumann_entropy`
  src/qibo/quantum_info/entropies.py
  tests/test_callbacks.py
Labels: bug, quantum_info module

#1326 Add `Phase-RX` gate + `qasm_label` for `GPI`, `GPI2`, and `MS` gates
  doc/source/api-reference/qibo.rst
  src/qibo/backends/npmatrices.py
  src/qibo/gates/abstract.py
  src/qibo/gates/gates.py
  src/qibo/transpiler/decompositions.py
  tests/test_gates_gates.py
Labels: documentation, enhancement

#1359 Fix to logic in `quantum_info.hamming_distance`
  src/qibo/quantum_info/utils.py
Labels: bug, quantum_info module

#1367 Fix `Gate.matrix` and `Circuit.unitary` in the presence of `Gate.controlled_by` method
  src/qibo/backends/abstract.py
  src/qibo/backends/numpy.py
  src/qibo/gates/abstract.py
  src/qibo/models/circuit.py
  tests/test_backends.py
  tests/test_gates_gates.py
  tests/test_models_circuit_features.py
Labels: bug

#1372 Addition of linear algebra `operations` submodule to `quantum_info` module
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/__init__.py
  src/qibo/quantum_info/operations.py
  tests/test_quantum_info_operations.py
Labels: documentation, enhancement, quantum_info module

#1369 Fix transpiler bugs about moved measurements and duplicated gates
  src/qibo/models/error_mitigation.py
  src/qibo/transpiler/pipeline.py
  src/qibo/transpiler/placer.py
  src/qibo/transpiler/router.py
  src/qibo/transpiler/unroller.py
  tests/test_transpiler_pipeline.py
  tests/test_transpiler_placer.py
  tests/test_transpiler_router.py
  tests/test_transpiler_unroller.py
Labels: bug, transpiler
