Repository qiboteam/qibo, pull requests merged in 2024-01, with the labels that each got.

#1146 Add `seed` parameter to `quantum_info.entangling_capacity`
  src/qibo/quantum_info/metrics.py
  tests/test_quantum_info_metrics.py
Labels: enhancement

#1134 Add labels to circuit wires
  src/qibo/models/circuit.py
  tests/test_models_circuit.py
Labels: documentation, enhancement

#1139 Add `Clifford.to_circuit` and `Clifford.copy` methods + initialization via circuits
  doc/source/api-reference/qibo.rst
  src/qibo/backends/clifford.py
  src/qibo/quantum_info/_clifford_utils.py
  src/qibo/quantum_info/clifford.py
  tests/test_quantum_info_clifford.py
Labels: documentation, enhancement

#1141 Add `diagonal` architectute to deterministic Unary encoder
  src/qibo/models/encodings.py
  tests/test_models_encodings.py
Labels: documentation, enhancement

#1129 Quantum Error Mitigation: Readout, Importance Clifford Sampling
  doc/source/api-reference/qibo.rst
  doc/source/code-examples/advancedexamples.rst
  src/qibo/models/__init__.py
  src/qibo/models/error_mitigation.py
  tests/test_models_error_mitigation.py
Labels: documentation, enhancement

#1160 Minor documentation fixes
  doc/source/api-reference/qibo.rst
  src/qibo/noise.py
  src/qibo/quantum_info/metrics.py
Labels: documentation

#1166 Fix test failing and remove unnecessary prints from tests
  tests/test_backends_clifford.py
  tests/test_measurements.py
  tests/test_quantum_info_random.py
  tests/test_transpiler_blocks.py
Labels: bug, quantum_info module

#1177 Add (quantum) `relative_entropy` to `quantum_info.entropies`
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/entanglement.py
  src/qibo/quantum_info/entropies.py
  tests/test_quantum_info_entropies.py
Labels: documentation, enhancement, quantum_info module

#1179 Add `renyi_entropy` and `classical_renyi_entropy` to `quantum_info.entropies`
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/entropies.py
  tests/test_quantum_info_entropies.py
Labels: documentation, enhancement, quantum_info module

#1159 Create `quantum_info.hamming_distance`
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/utils.py
  tests/test_quantum_info_utils.py
Labels: documentation, enhancement, quantum_info module

#1182 Add `tsallis_entropy` and `classical_tsallis_entropy` to `quantum_info.entropies`
  doc/source/api-reference/qibo.rst
  src/qibo/quantum_info/entropies.py
  tests/test_quantum_info_entropies.py
Labels: documentation, enhancement, quantum_info module
