Repository qiboteam/qibo, pull requests merged in 2024-12, with the labels that each got.

#1538 Add general `Heisenberg` Hamiltonian and `XXX` model
  doc/source/api-reference/qibo.rst
  src/qibo/hamiltonians/__init__.py
  src/qibo/hamiltonians/models.py
  tests/test_hamiltonians_models.py
Labels: documentation, enhancement

#1539 Fix import in Advanced Examples
  doc/source/code-examples/advancedexamples.rst
Labels: bug, documentation

#1531 Update Documentation for `wire_names` and `_Global`
  doc/source/api-reference/qibo.rst
  doc/source/code-examples/advancedexamples.rst
  src/qibo/models/circuit.py
  src/qibo/transpiler/__init__.py
  src/qibo/transpiler/abstract.py
  src/qibo/transpiler/asserts.py
  src/qibo/transpiler/optimizer.py
  src/qibo/transpiler/pipeline.py
  src/qibo/transpiler/placer.py
  src/qibo/transpiler/router.py
  src/qibo/transpiler/unroller.py
  tests/test_transpiler_asserts.py
  tests/test_transpiler_pipeline.py
  tests/test_transpiler_router.py
Labels: documentation

#1544 Fix documentation of `models.circuit.Circuit`
  src/qibo/models/circuit.py
Labels: documentation

#1547 Add decomposition for `gates.CRY`
  src/qibo/gates/gates.py
  src/qibo/transpiler/decompositions.py
  tests/test_gates_gates.py
Labels: enhancement, transpiler

#1549 Minor fix to qibo.transpiler.placer.Subgraph
  src/qibo/transpiler/placer.py
  tests/test_transpiler_placer.py
Labels: run-workflow
