Repository qiboteam/qibo, pull requests merged in 2025-07, with the labels that each got.

#1684 Add `Backend.calculate_matrix_log` and `Backend.calculate_matrix_sqrt` + refactor `Backend.calculate_matrix_exp` + add `quantum_info.matrix_logarithm` and `quantum_info.matrix_sqrt`
  doc/source/api-reference/qibo.rst
  src/qibo/backends/abstract.py
  src/qibo/backends/numpy.py
  src/qibo/callbacks.py
  src/qibo/hamiltonians/hamiltonians.py
  src/qibo/hamiltonians/terms.py
  src/qibo/quantum_info/entanglement.py
  src/qibo/quantum_info/entropies.py
  src/qibo/quantum_info/linalg_operations.py
  src/qibo/quantum_info/metrics.py
  tests/test_quantum_info_entanglement.py
  tests/test_quantum_info_entropies.py
  tests/test_quantum_info_linalg_operations.py
  tests/test_quantum_info_metrics.py
Labels: documentation, enhancement, quantum_info module, refactor

#1672 added plot state function for issue #689
  doc/source/code-examples/examples.rst
  src/qibo/ui/__init__.py
  src/qibo/ui/result_visualization.py
  tests/test_plot_state_ui_images/test_complex_circuit_state_nqubits_2.png
  tests/test_plot_state_ui_images/test_simple_circuit_state_colors_nqubits_2.png
  tests/test_plot_state_ui_images/test_simple_circuit_state_hadamard_nqubits_2.png
  tests/test_plot_state_ui_images/test_simple_circuit_state_nqubits_2.png
  tests/test_plot_state_ui_images/test_simple_circuit_state_relevant_components_nqubits_2.png
  tests/test_plot_state_ui_images/test_title_circuit_state_nqubits_3.png
  tests/test_ui_plot_state.py
  tests/utils.py
Labels: enhancement, run-workflow

#1694 Permutation synthesis and Li's sparse encoder
  doc/source/api-reference/qibo.rst
  src/qibo/models/__init__.py
  src/qibo/models/encodings.py
  src/qibo/quantum_info/utils.py
  tests/test_models_encodings.py
  tests/test_quantum_info_utils.py
Labels: documentation, enhancement, run-workflow

#1686 Support simultaneously diagonalizable terms in ``exp_from_circuit``
  src/qibo/hamiltonians/hamiltonians.py
  src/qibo/hamiltonians/terms.py
  tests/test_hamiltonians.py
Labels: enhancement
