Repository qiboteam/qibo, pull requests merged in 2025-06, with the labels that each got.

#1660 Expectation from samples improvements
  src/qibo/hamiltonians/hamiltonians.py
Labels: refactor

#1654 [UnitaryHack2025] Implement all-to-all and simple Dicke State generation circuits
  doc/source/api-reference/qibo.rst
  src/qibo/models/encodings.py
  tests/test_models_encodings.py
Labels: run-workflow, unitaryHACK 2025

#1670 Enable `TOFFOLI.decompose` and add `CCZ` decomposition into native gate set that includes the `CZ` gate
  src/qibo/gates/gates.py
  src/qibo/transpiler/decompositions.py
  src/qibo/transpiler/unroller.py
  tests/test_gates_abstract.py
Labels: bug, enhancement, transpiler

#1674 Adding `_check_backend` to CMA optimizer
  src/qibo/optimizers.py
Labels: bug

#1625 Allowing circuit execution using `float32` and `float64` dtypes
  doc/source/code-examples/advancedexamples.rst
  doc/source/code-examples/examples.rst
  examples/benchmarks/evolution.py
  examples/benchmarks/example.sh
  examples/benchmarks/main.py
  examples/benchmarks/qaoa.py
  examples/benchmarks/results/PRECISION.md
  examples/benchmarks/vqe.py
  examples/test_examples.py
  poetry.lock
  src/qibo/__init__.py
  src/qibo/backends/__init__.py
  src/qibo/backends/abstract.py
  src/qibo/backends/npmatrices.py
  src/qibo/backends/numpy.py
  src/qibo/backends/qulacs.py
  src/qibo/derivative.py
  src/qibo/hamiltonians/hamiltonians.py
  src/qibo/measurements.py
  src/qibo/models/error_mitigation.py
  src/qibo/models/variational.py
  src/qibo/quantum_info/random_ensembles.py
  src/qibo/result.py
  src/qibo/symbols.py
  tests/test_backends_global.py
  tests/test_derivative.py
  tests/test_hamiltonians_symbolic.py
  tests/test_models_error_mitigation.py
  tests/test_quantum_info_random.py
  tests/test_quantum_info_superoperator_transformations.py
  tests/test_quantum_info_utils.py
Labels: documentation, enhancement
