Repository qiboteam/qibo, pull requests merged in 2025-03, with the labels that each got.

#1594 Fix `gates.GeneralizedRBS.apply` method
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: bug, run-on-sim

#1599 Matrix representation of `gates.GeneralizedRBS` independent of qubit order
  src/qibo/backends/npmatrices.py
  src/qibo/gates/gates.py
  tests/test_gates_gates.py
Labels: bug

#1582 Migrating to Numpy 2.0
  .github/workflows/deploy.yml
  .github/workflows/rules.yml
  poetry.lock
  pyproject.toml
  src/qibo/backends/_clifford_operations.py
  src/qibo/backends/clifford.py
  src/qibo/backends/npmatrices.py
  src/qibo/backends/numpy.py
  src/qibo/hamiltonians/hamiltonians.py
  src/qibo/models/hep.py
  src/qibo/quantum_info/_clifford_utils.py
  tests/conftest.py
  tests/test_backends.py
  tests/test_cirq.py
  tests/test_models_circuit_backpropagation.py
  tests/test_models_circuit_parametrized.py
  tests/test_models_circuit_qasm_cirq.py
Labels: enhancement, dependencies

#1484 Support Python 3.13
  .github/workflows/deploy.yml
  .github/workflows/publish.yml
  .github/workflows/rules.yml
  .github/workflows/selfhosted.yml
  flake.lock
  poetry.lock
  pyproject.toml
  src/qibo/models/circuit.py
  tests/test_backends.py
  tests/test_backends_qibotn.py
Labels: enhancement, dependencies

#1608 Fix clustering bug when plotting single-qubit circuits
  src/qibo/ui/mpldrawer.py
Labels: bug, run-workflow

#1584 Add `binary_encoder` parameterized in hyperspherical coordinates
  src/qibo/models/encodings.py
  src/qibo/tomography/gate_set_tomography.py
  tests/test_models_encodings.py
Labels: documentation, enhancement, run-on-sim

#1610 bug fix #1609
  src/qibo/ui/mpldrawer.py
  tests/test_ui_array_images/test_fuse_cluster.npy
Labels: bug, run-workflow

#1612 custom labels for plot_circuit drawing function - issue #1611
  src/qibo/ui/mpldrawer.py
Labels: run-workflow

#1614 Fix `Circuit.get_parameters(format="flatlist")` in the presence of 0-dimensional tensors
  src/qibo/models/circuit.py
  tests/test_models_circuit.py
Labels: bug

#1604 Add Lanczos algorithm to `quantum_info.linalg_operations`
  doc/source/api-reference/qibo.rst
  poetry.lock
  src/qibo/quantum_info/linalg_operations.py
  tests/test_quantum_info_linalg_operations.py
Labels: enhancement, run-on-sim, quantum_info module

#1615 Make ``backend.samples_to_binary`` use the backend's engine
  poetry.lock
  src/qibo/backends/numpy.py
Labels: run-on-sim
