Repository qiboteam/qibo, pull requests merged in 2025-04, with the labels that each got.

#1623 review plot out of bounds qubit number - bug #1497
  src/qibo/ui/mpldrawer.py
Labels: run-workflow

#1616 ``pytest --gpu-only`` fix + GPU backends shots sampling
  poetry.lock
  src/qibo/backends/abstract.py
  src/qibo/backends/numpy.py
  src/qibo/measurements.py
  src/qibo/quantum_info/clifford.py
  src/qibo/result.py
  tests/conftest.py
  tests/test_measurements_probabilistic.py
  tests/test_models_circuit_features.py
  tests/test_models_tsp.py
Labels: run-on-sim

#1622 Making functions in `models.encodings` backend-aware
  src/qibo/models/encodings.py
  src/qibo/quantum_info/utils.py
  tests/test_models_encodings.py
  tests/test_quantum_info_utils.py
Labels: enhancement, run-on-sim

#1591 Add `sparse_encoder` to `models.encodings`
  doc/source/api-reference/qibo.rst
  poetry.lock
  src/qibo/gates/gates.py
  src/qibo/models/__init__.py
  src/qibo/models/encodings.py
  src/qibo/quantum_info/utils.py
  tests/test_models_encodings.py
  tests/test_quantum_info_utils.py
Labels: documentation, enhancement, run-on-sim

#1629 Drop `noise_model.py`
  poetry.lock
  pyproject.toml
  src/qibo/noise_model.py
Labels: run-on-sim

#1628 Downgrade `sympy` dependency
  poetry.lock
  pyproject.toml
Labels: dependencies, run-on-sim
