Repository qiboteam/qibo, pull requests merged in 2025-01, with the labels that each got.

#1551 Add `models.encodings.binary_encoder` for real-valued data
  doc/source/api-reference/qibo.rst
  src/qibo/models/encodings.py
  tests/test_models_encodings.py
Labels: documentation, enhancement

#1555 Fix bug in `qasm` parser when `gates.U3` is present.
  src/qibo/models/_openqasm.py
  tests/test_models_circuit_qasm.py
Labels: bug

#1563 Improving docstrings in final qubit mapping, w/ `{logical: physical}`
  src/qibo/transpiler/abstract.py
  src/qibo/transpiler/asserts.py
  src/qibo/transpiler/pipeline.py
  src/qibo/transpiler/router.py
Labels: run-workflow

#1560 Add `hamming_weight_encoder` to `models.encodings`
  doc/source/api-reference/qibo.rst
  src/qibo/models/__init__.py
  src/qibo/models/encodings.py
  tests/test_models_encodings.py
Labels: documentation, enhancement

#1567 Fix `StarConnectivtyPlacer/Router._check_star_connectivity` for `len(nodes)>5`
  src/qibo/transpiler/placer.py
  src/qibo/transpiler/router.py
  tests/test_transpiler_placer.py
  tests/test_transpiler_router.py
Labels: bug

#1559 Add nontrivial entangling layers to `models.encodings.entangling_layer`
  doc/source/api-reference/qibo.rst
  src/qibo/models/encodings.py
  src/qibo/transpiler/asserts.py
  tests/test_models_encodings.py
  tests/test_transpiler_placer.py
  tests/test_transpiler_router.py
Labels: documentation, enhancement

#1561 Selfhosted GPU workflow and GPU Tests fixes
  poetry.lock
  pyproject.toml
  src/qibo/backends/clifford.py
  tests/test_backends_qibotn.py
  tests/test_tomography_gate_set_tomography.py
Labels: tests
