Repository qiboteam/qibo, pull requests merged in 2025-02, with the labels that each got.

#1572 Modify `models.encodings.hamming_weight_encoder` to upload data in the lexicographical order
  src/qibo/models/encodings.py
  tests/test_models_encodings.py
Labels: enhancement

#1571 Fix docstring of `gates.PRX`
  src/qibo/gates/gates.py
Labels: documentation

#1573 Updating cuquantum version
  poetry.lock
  src/qibo/backends/npmatrices.py
  src/qibo/transpiler/unitary_decompositions.py
  tests/test_backends.py
  tests/test_transpiler_unitary_decompositions.py
Labels: run-on-sim

#1558 Cupy matrices
  poetry.lock
  pyproject.toml
  src/qibo/backends/clifford.py
  src/qibo/backends/npmatrices.py
  src/qibo/optimizers.py
  src/qibo/quantum_info/_clifford_utils.py
  src/qibo/tomography/gate_set_tomography.py
  src/qibo/transpiler/unitary_decompositions.py
  tests/test_backends.py
  tests/test_backends_clifford.py
  tests/test_backends_qibotn.py
  tests/test_models_variational.py
  tests/test_quantum_info_clifford.py
  tests/test_quantum_info_entropies.py
  tests/test_tomography_gate_set_tomography.py
  tests/test_transpiler_unitary_decompositions.py
Labels: run-on-sim

#1578 Changed the directory to selfhosted tests to ``$(mktemp -d)``
  selfhosted
Labels: run-on-sim

#1579 Selfhosted GPU tests restricted to GPU backends only
  selfhosted
  tests/conftest.py
Labels: run-on-sim

#1597 Remove while loop in `error_sensitive_circuit`
  src/qibo/gates/gates.py
  src/qibo/models/error_mitigation.py
Labels: run-on-sim
